##### 开启 Spring Boot 的 Override 机制
spring:
  main:
    allow-bean-definition-overriding: true
##### 配置 Eureka Server 链接地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000