##### 项目启动端口号
server:
  port: 11001
spring:
  ##### 项目应用名
  application:
    name: witmed-patient-provider
  ##### 需要加载的配置文件
  profiles:
    active: data,client,mail
ribbon:
  eureka:
    enabled: true